configuration:
    database_host: localhost
    database_port: null
    database_name: p3
    database_user: root
    database_password: root
    local: fr
    template: Twig
    development: true
    folder: false # If Kinto-Un is not at the root of the domain

security:
    token: 
    expire: 30

login:
    login: name
    password: password
    activation: false
    remember: false
    session: id|name

translate:
    type: json
    dbTable: 